//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPL2.ServiceBookStore {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Libro", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Libro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCPL2.ServiceBookStore.Editorial EditorialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IDEditorialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IDLibroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short PaginasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PublicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> StockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autor {
            get {
                return this.AutorField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorField, value) != true)) {
                    this.AutorField = value;
                    this.RaisePropertyChanged("Autor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCPL2.ServiceBookStore.Editorial Editorial {
            get {
                return this.EditorialField;
            }
            set {
                if ((object.ReferenceEquals(this.EditorialField, value) != true)) {
                    this.EditorialField = value;
                    this.RaisePropertyChanged("Editorial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IDEditorial {
            get {
                return this.IDEditorialField;
            }
            set {
                if ((this.IDEditorialField.Equals(value) != true)) {
                    this.IDEditorialField = value;
                    this.RaisePropertyChanged("IDEditorial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IDLibro {
            get {
                return this.IDLibroField;
            }
            set {
                if ((this.IDLibroField.Equals(value) != true)) {
                    this.IDLibroField = value;
                    this.RaisePropertyChanged("IDLibro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN {
            get {
                return this.ISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.ISBNField, value) != true)) {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Imagen {
            get {
                return this.ImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenField, value) != true)) {
                    this.ImagenField = value;
                    this.RaisePropertyChanged("Imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Paginas {
            get {
                return this.PaginasField;
            }
            set {
                if ((this.PaginasField.Equals(value) != true)) {
                    this.PaginasField = value;
                    this.RaisePropertyChanged("Paginas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Publicacion {
            get {
                return this.PublicacionField;
            }
            set {
                if ((this.PublicacionField.Equals(value) != true)) {
                    this.PublicacionField = value;
                    this.RaisePropertyChanged("Publicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Editorial", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Editorial : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string E_mailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IDEditorialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MVCPL2.ServiceBookStore.Libro[] LibrosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string E_mail {
            get {
                return this.E_mailField;
            }
            set {
                if ((object.ReferenceEquals(this.E_mailField, value) != true)) {
                    this.E_mailField = value;
                    this.RaisePropertyChanged("E_mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IDEditorial {
            get {
                return this.IDEditorialField;
            }
            set {
                if ((this.IDEditorialField.Equals(value) != true)) {
                    this.IDEditorialField = value;
                    this.RaisePropertyChanged("IDEditorial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MVCPL2.ServiceBookStore.Libro[] Libros {
            get {
                return this.LibrosField;
            }
            set {
                if ((object.ReferenceEquals(this.LibrosField, value) != true)) {
                    this.LibrosField = value;
                    this.RaisePropertyChanged("Libros");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Web {
            get {
                return this.WebField;
            }
            set {
                if ((object.ReferenceEquals(this.WebField, value) != true)) {
                    this.WebField = value;
                    this.RaisePropertyChanged("Web");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAllDataSP", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class GetAllDataSP : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripciónField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirecciónField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EditorialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IDLibroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PublicaciónField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short PáginasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> StockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeléfonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TítuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autor {
            get {
                return this.AutorField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorField, value) != true)) {
                    this.AutorField = value;
                    this.RaisePropertyChanged("Autor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripción {
            get {
                return this.DescripciónField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripciónField, value) != true)) {
                    this.DescripciónField = value;
                    this.RaisePropertyChanged("Descripción");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dirección {
            get {
                return this.DirecciónField;
            }
            set {
                if ((object.ReferenceEquals(this.DirecciónField, value) != true)) {
                    this.DirecciónField = value;
                    this.RaisePropertyChanged("Dirección");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Editorial {
            get {
                return this.EditorialField;
            }
            set {
                if ((object.ReferenceEquals(this.EditorialField, value) != true)) {
                    this.EditorialField = value;
                    this.RaisePropertyChanged("Editorial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IDLibro {
            get {
                return this.IDLibroField;
            }
            set {
                if ((this.IDLibroField.Equals(value) != true)) {
                    this.IDLibroField = value;
                    this.RaisePropertyChanged("IDLibro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN {
            get {
                return this.ISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.ISBNField, value) != true)) {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Publicación {
            get {
                return this.PublicaciónField;
            }
            set {
                if ((this.PublicaciónField.Equals(value) != true)) {
                    this.PublicaciónField = value;
                    this.RaisePropertyChanged("Publicación");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Páginas {
            get {
                return this.PáginasField;
            }
            set {
                if ((this.PáginasField.Equals(value) != true)) {
                    this.PáginasField = value;
                    this.RaisePropertyChanged("Páginas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Teléfono {
            get {
                return this.TeléfonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TeléfonoField, value) != true)) {
                    this.TeléfonoField = value;
                    this.RaisePropertyChanged("Teléfono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Título {
            get {
                return this.TítuloField;
            }
            set {
                if ((object.ReferenceEquals(this.TítuloField, value) != true)) {
                    this.TítuloField = value;
                    this.RaisePropertyChanged("Título");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Web {
            get {
                return this.WebField;
            }
            set {
                if ((object.ReferenceEquals(this.WebField, value) != true)) {
                    this.WebField = value;
                    this.RaisePropertyChanged("Web");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceBookStore.IBookStore")]
    public interface IBookStore {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStore/CreateBook", ReplyAction="http://tempuri.org/IBookStore/CreateBookResponse")]
        MVCPL2.ServiceBookStore.Libro CreateBook(MVCPL2.ServiceBookStore.Libro newBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStore/CreateBook", ReplyAction="http://tempuri.org/IBookStore/CreateBookResponse")]
        System.Threading.Tasks.Task<MVCPL2.ServiceBookStore.Libro> CreateBookAsync(MVCPL2.ServiceBookStore.Libro newBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStore/RetrieveBookByID", ReplyAction="http://tempuri.org/IBookStore/RetrieveBookByIDResponse")]
        MVCPL2.ServiceBookStore.Libro RetrieveBookByID(short ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStore/RetrieveBookByID", ReplyAction="http://tempuri.org/IBookStore/RetrieveBookByIDResponse")]
        System.Threading.Tasks.Task<MVCPL2.ServiceBookStore.Libro> RetrieveBookByIDAsync(short ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStore/UpdateBook", ReplyAction="http://tempuri.org/IBookStore/UpdateBookResponse")]
        bool UpdateBook(MVCPL2.ServiceBookStore.Libro bookToUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStore/UpdateBook", ReplyAction="http://tempuri.org/IBookStore/UpdateBookResponse")]
        System.Threading.Tasks.Task<bool> UpdateBookAsync(MVCPL2.ServiceBookStore.Libro bookToUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStore/DeleteBook", ReplyAction="http://tempuri.org/IBookStore/DeleteBookResponse")]
        bool DeleteBook(short ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStore/DeleteBook", ReplyAction="http://tempuri.org/IBookStore/DeleteBookResponse")]
        System.Threading.Tasks.Task<bool> DeleteBookAsync(short ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStore/GetAllBooks", ReplyAction="http://tempuri.org/IBookStore/GetAllBooksResponse")]
        MVCPL2.ServiceBookStore.Libro[] GetAllBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStore/GetAllBooks", ReplyAction="http://tempuri.org/IBookStore/GetAllBooksResponse")]
        System.Threading.Tasks.Task<MVCPL2.ServiceBookStore.Libro[]> GetAllBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStore/GetAllEditoriales", ReplyAction="http://tempuri.org/IBookStore/GetAllEditorialesResponse")]
        MVCPL2.ServiceBookStore.Editorial[] GetAllEditoriales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStore/GetAllEditoriales", ReplyAction="http://tempuri.org/IBookStore/GetAllEditorialesResponse")]
        System.Threading.Tasks.Task<MVCPL2.ServiceBookStore.Editorial[]> GetAllEditorialesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStore/GetAllRecord", ReplyAction="http://tempuri.org/IBookStore/GetAllRecordResponse")]
        MVCPL2.ServiceBookStore.GetAllDataSP[] GetAllRecord();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStore/GetAllRecord", ReplyAction="http://tempuri.org/IBookStore/GetAllRecordResponse")]
        System.Threading.Tasks.Task<MVCPL2.ServiceBookStore.GetAllDataSP[]> GetAllRecordAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStore/FilterBookByEditorialID", ReplyAction="http://tempuri.org/IBookStore/FilterBookByEditorialIDResponse")]
        MVCPL2.ServiceBookStore.Libro[] FilterBookByEditorialID(short IDCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStore/FilterBookByEditorialID", ReplyAction="http://tempuri.org/IBookStore/FilterBookByEditorialIDResponse")]
        System.Threading.Tasks.Task<MVCPL2.ServiceBookStore.Libro[]> FilterBookByEditorialIDAsync(short IDCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStore/FilterBookByTitulo", ReplyAction="http://tempuri.org/IBookStore/FilterBookByTituloResponse")]
        MVCPL2.ServiceBookStore.Libro[] FilterBookByTitulo(string titulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStore/FilterBookByTitulo", ReplyAction="http://tempuri.org/IBookStore/FilterBookByTituloResponse")]
        System.Threading.Tasks.Task<MVCPL2.ServiceBookStore.Libro[]> FilterBookByTituloAsync(string titulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStore/CreateEditorial", ReplyAction="http://tempuri.org/IBookStore/CreateEditorialResponse")]
        MVCPL2.ServiceBookStore.Editorial CreateEditorial(MVCPL2.ServiceBookStore.Editorial newEditorial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStore/CreateEditorial", ReplyAction="http://tempuri.org/IBookStore/CreateEditorialResponse")]
        System.Threading.Tasks.Task<MVCPL2.ServiceBookStore.Editorial> CreateEditorialAsync(MVCPL2.ServiceBookStore.Editorial newEditorial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStore/FilterBookByEditorial", ReplyAction="http://tempuri.org/IBookStore/FilterBookByEditorialResponse")]
        MVCPL2.ServiceBookStore.Libro[] FilterBookByEditorial(string nombreEditorial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookStore/FilterBookByEditorial", ReplyAction="http://tempuri.org/IBookStore/FilterBookByEditorialResponse")]
        System.Threading.Tasks.Task<MVCPL2.ServiceBookStore.Libro[]> FilterBookByEditorialAsync(string nombreEditorial);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookStoreChannel : MVCPL2.ServiceBookStore.IBookStore, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookStoreClient : System.ServiceModel.ClientBase<MVCPL2.ServiceBookStore.IBookStore>, MVCPL2.ServiceBookStore.IBookStore {
        
        public BookStoreClient() {
        }
        
        public BookStoreClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookStoreClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookStoreClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookStoreClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MVCPL2.ServiceBookStore.Libro CreateBook(MVCPL2.ServiceBookStore.Libro newBook) {
            return base.Channel.CreateBook(newBook);
        }
        
        public System.Threading.Tasks.Task<MVCPL2.ServiceBookStore.Libro> CreateBookAsync(MVCPL2.ServiceBookStore.Libro newBook) {
            return base.Channel.CreateBookAsync(newBook);
        }
        
        public MVCPL2.ServiceBookStore.Libro RetrieveBookByID(short ID) {
            return base.Channel.RetrieveBookByID(ID);
        }
        
        public System.Threading.Tasks.Task<MVCPL2.ServiceBookStore.Libro> RetrieveBookByIDAsync(short ID) {
            return base.Channel.RetrieveBookByIDAsync(ID);
        }
        
        public bool UpdateBook(MVCPL2.ServiceBookStore.Libro bookToUpdate) {
            return base.Channel.UpdateBook(bookToUpdate);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateBookAsync(MVCPL2.ServiceBookStore.Libro bookToUpdate) {
            return base.Channel.UpdateBookAsync(bookToUpdate);
        }
        
        public bool DeleteBook(short ID) {
            return base.Channel.DeleteBook(ID);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteBookAsync(short ID) {
            return base.Channel.DeleteBookAsync(ID);
        }
        
        public MVCPL2.ServiceBookStore.Libro[] GetAllBooks() {
            return base.Channel.GetAllBooks();
        }
        
        public System.Threading.Tasks.Task<MVCPL2.ServiceBookStore.Libro[]> GetAllBooksAsync() {
            return base.Channel.GetAllBooksAsync();
        }
        
        public MVCPL2.ServiceBookStore.Editorial[] GetAllEditoriales() {
            return base.Channel.GetAllEditoriales();
        }
        
        public System.Threading.Tasks.Task<MVCPL2.ServiceBookStore.Editorial[]> GetAllEditorialesAsync() {
            return base.Channel.GetAllEditorialesAsync();
        }
        
        public MVCPL2.ServiceBookStore.GetAllDataSP[] GetAllRecord() {
            return base.Channel.GetAllRecord();
        }
        
        public System.Threading.Tasks.Task<MVCPL2.ServiceBookStore.GetAllDataSP[]> GetAllRecordAsync() {
            return base.Channel.GetAllRecordAsync();
        }
        
        public MVCPL2.ServiceBookStore.Libro[] FilterBookByEditorialID(short IDCategory) {
            return base.Channel.FilterBookByEditorialID(IDCategory);
        }
        
        public System.Threading.Tasks.Task<MVCPL2.ServiceBookStore.Libro[]> FilterBookByEditorialIDAsync(short IDCategory) {
            return base.Channel.FilterBookByEditorialIDAsync(IDCategory);
        }
        
        public MVCPL2.ServiceBookStore.Libro[] FilterBookByTitulo(string titulo) {
            return base.Channel.FilterBookByTitulo(titulo);
        }
        
        public System.Threading.Tasks.Task<MVCPL2.ServiceBookStore.Libro[]> FilterBookByTituloAsync(string titulo) {
            return base.Channel.FilterBookByTituloAsync(titulo);
        }
        
        public MVCPL2.ServiceBookStore.Editorial CreateEditorial(MVCPL2.ServiceBookStore.Editorial newEditorial) {
            return base.Channel.CreateEditorial(newEditorial);
        }
        
        public System.Threading.Tasks.Task<MVCPL2.ServiceBookStore.Editorial> CreateEditorialAsync(MVCPL2.ServiceBookStore.Editorial newEditorial) {
            return base.Channel.CreateEditorialAsync(newEditorial);
        }
        
        public MVCPL2.ServiceBookStore.Libro[] FilterBookByEditorial(string nombreEditorial) {
            return base.Channel.FilterBookByEditorial(nombreEditorial);
        }
        
        public System.Threading.Tasks.Task<MVCPL2.ServiceBookStore.Libro[]> FilterBookByEditorialAsync(string nombreEditorial) {
            return base.Channel.FilterBookByEditorialAsync(nombreEditorial);
        }
    }
}
